name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:13-alpine
        ports:
          - 5434:5432
        env:
          POSTGRES_DB: rest_api_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && pytest"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"